version: '3.8'

services:
  raft-node-0:
    image: thaivan/cafe-raft:latest
    container_name: raft-node-0
    environment:
      - CLUSTER_PROPERTIES_NODES=http://raft-node-0:8080,http://raft-node-1:8080,http://raft-node-2:8080
      - CLUSTER_PROPERTIES_NODEID=0
      - CLUSTER_PROPERTIES_BASEDISK=disk-node-0
    ports:
      - "8080:8080"
    volumes:
      - raft-node-0-data:/disk-node-0
    networks:
      - raft-network

  raft-node-1:
    image: thaivan/cafe-raft:latest
    container_name: raft-node-1
    environment:
      - CLUSTER_PROPERTIES_NODES=http://raft-node-0:8080,http://raft-node-1:8080,http://raft-node-2:8080
      - CLUSTER_PROPERTIES_NODEID=1
      - CLUSTER_PROPERTIES_BASEDISK=disk-node-1
    ports:
      - "8081:8080"
    volumes:
      - raft-node-1-data:/disk-node-1
    networks:
      - raft-network

  raft-node-2:
    image: thaivan/cafe-raft:latest
    container_name: raft-node-2
    environment:
      - CLUSTER_PROPERTIES_NODES=http://raft-node-0:8080,http://raft-node-1:8080,http://raft-node-2:8080
      - CLUSTER_PROPERTIES_NODEID=2
      - CLUSTER_PROPERTIES_BASEDISK=disk-node-2
    ports:
      - "8082:8080"
    volumes:
      - raft-node-2-data:/disk-node-2
    networks:
      - raft-network

volumes:
  raft-node-0-data:
  raft-node-1-data:
  raft-node-2-data:

networks:
  raft-network:
    driver: bridge
