udp:
  nodes:
    hosts:
      localhost,localhost,localhost
    ports:
      11111,11112,11113

cluster.properties:
  queue-size: 4096
  nodeId: 0
  nodes:
    - http://localhost:8080
    - http://localhost:8081
    - http://localhost:8082
  base-disk: disk-node-${cluster.properties.nodeId}

  # class | arg0 | arg1...
  idle-strategy: SleepIdleStrategy|1000
  electionTimeoutMs: # 150 - 300
    - 150
    - 300
  heartbeatTimeoutMs: 100 # 50 - 150
  heartbeatIntervalMs: 80 # must be smaller than heartbeatTimeoutMs
  nextSendLogTimeoutMs: 10 # should be smaller than heartbeatTimeoutMs
  messageBatchSize: 10
  commitedLogBatchSize: 10000
  appendLogBatchSize: 10
